name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

  deploy-aws:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure SSH
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
      env:
          SSH_HOST: "34.201.145.161"
          SSH_USER: "ubuntu"
          SSH_KEY: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
    - name: Deployment
      uses: appleboy/ssh-action@master
      with:
        host: "34.201.145.161"
        key: ${{secrets.AWS_EC2_SSH_PRIVATE_KEY}}
        username: "ubuntu"
        script: |
          cd /var/www/sureOdds-backend/
          ./prod_server_deploy.sh
