name: Deploy to EC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-aws:

    runs-on: ubuntu-latest

    steps:

    - name: Execute type checking
      run: vendor/bin/phpstan analyse

    - name: Run tests
      run: ./vendor/bin/pest --parallel --coverage --min=50
      env:
          APP_ENV: testing

    - name: Checkout
      uses: actions/checkout@v2
    - name: Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        #passphrase: ${{ secrets.SSH_PASSPHASE }}
        username: "ubuntu"
        script: |
          cd /var/www/sureodds_backend/staging
          ./prod_server_deploy.sh

